apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-12-12T08:22:51Z"
  generation: 1
  labels:
    app: asia
  name: asia
  namespace: world
  resourceVersion: "1298"
  uid: 34afb7cc-9b30-4243-95b4-b39d0b893090
spec:
  progressDeadlineSeconds: 600   #如果 Deployment 在指定时间内未能达到预期状态，则被视为失败。
  replicas: 2                   # Pod副本数量
  revisionHistoryLimit: 10      #历史版本限制,保留10个回滚记录
  selector:                     # 标签选择器,通过app:asia来识别该Deployment中Pod启动的数量,与RS,RC下启动的同Label的pod无关,不受影响.
    matchLabels:
      app: asia
  strategy:                     #升级策略
    rollingUpdate:              #滚动升级
      maxSurge: 25%             #超出期望数最大的百分比,如replicas=4,则滚动升级时最多会有1个pod超出,即滚动升级期间该Deployment可能出现5个pod
      maxUnavailable: 25%       #最大可以停用pod的百分比,不可用的pod不可以超过25%
    type: RollingUpdate         #滚动升级
  template:
    metadata:                   #该deployment下启动的pod的基础数据
      creationTimestamp: null
      labels:
        app: asia
    spec:
      containers:
      - image: nginx:1.21.5-alpine
        imagePullPolicy: IfNotPresent
        name: c
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
        - mountPath: /etc/nginx
          name: nginx-conf
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - echo 'hello, you reached ASIA' > /html/index.html
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        name: init-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /html
          name: html
      restartPolicy: Always                     #pod失败时重启策略,永远重启
      schedulerName: default-scheduler          #执行该Deploment调度任务的调度器名称,默认调度器
      securityContext: {}
      terminationGracePeriodSeconds: 30         #容器在终止前等待的格林时间:30秒
      volumes:
      - emptyDir: {}
        name: html
      - configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          name: nginx-conf
        name: nginx-conf
