apiVersion: v1
kind: Service                               #类型为Service资源对象
metadata:
  name: europe                               #Service名为europe
spec:
  type: NodePort
  ports: 
  - port: 80                                #Service对外提供的端口是80
    targetPort: 80                          #Pod端口是80
  selector:
    app: europe
