apiVersion: v1
kind: Pod
metadata:
  name: mongodb-nfs
spec:
  volumes:
  - name: mongodb-data
    nfs:
      server: 172.16.17.7
      path: /data/nfs
  nodeSelector:
    kubernetes.io/hostname: "node-2"
  containers:
  - image: mongo:4.0
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
