apiVersion: v1
kind: Service                               #类型为Service资源对象
metadata:
  name: asia                               #Service名为asia
spec:
  ports: 
  - port: 80                                #Service对外提供的端口是80
    targetPort: 80                           #Pod端口是80
  selector:
    app: asia
